import = [
  "/usr/local/lib/node_modules/alacritty-themes/themes/Monokai-Pro.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

  [window.padding]
  x = 10
  y = 10

[font]
size = 15

  [font.normal]
  family = "MesloLGS Nerd Font Mono"
